apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - name: upload-service
        image: cr.yandex/textbook-explainer/upload-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: YANDEX_CLOUD_KEY_ID
          valueFrom:
            secretKeyRef:
              name: yandex-cloud-credentials
              key: key-id
        - name: YANDEX_CLOUD_SECRET
          valueFrom:
            secretKeyRef:
              name: yandex-cloud-credentials
              key: secret
        - name: YANDEX_CLOUD_STORAGE_BUCKET
          value: "textbook-explainer-storage"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload-service
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
